# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantil < Formula
  desc "Mantil CLI"
  homepage ""
  version "0.1.2"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mantil-io/mantil/releases/download/v0.1.2/mantil_0.1.2_Darwin_x86_64.tar.gz", :using => S3DownloadStrategy
      sha256 "31d4cb6a6be20a30097021a1402f23ea47f06156128bed80e6e39aa46d489931"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mantil-io/mantil/releases/download/v0.1.2/mantil_0.1.2_Darwin_arm64.tar.gz", :using => S3DownloadStrategy
      sha256 "6094acf2a6d98d355b5f865992910897eb4ff2e9767e62194ff043d2b94a621a"
    end
  end

  depends_on "go"

  def install
    bin.install "mantil"
  end
end
