# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantil < Formula
  desc "Mantil CLI"
  homepage ""
  version "0.1.1"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mantil-io/mantil/releases/download/v0.1.1/mantil_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "a7dc4fa7058a3acdc19391054f69d0a3988760dbc4e5193a7c0a38a6e2d88876"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mantil-io/mantil/releases/download/v0.1.1/mantil_0.1.1_Darwin_arm64.tar.gz"
      sha256 "ae73844d928e3f790f6d149d2bbbeab19f82cee3ac1d236cc0cab7371693578f"
    end
  end

  def install
    bin.install "mantil"
  end
end
