# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantil < Formula
  desc "Mantil CLI"
  homepage ""
  version "0.1.20"

  on_macos do
    if Hardware::CPU.arm?
      url "releases.mantil.io/v0.1.20/mantil_0.1.20_Darwin_arm64.tar.gz"
      sha256 "994b2d570d63a0b97e65ea34b774927cc141863cbc1729283668bb18a7f45036"

      def install
        bin.install "mantil"
      end
    end
    if Hardware::CPU.intel?
      url "releases.mantil.io/v0.1.20/mantil_0.1.20_Darwin_x86_64.tar.gz"
      sha256 "95c76c27be5ffc9325cca407ef21340892770b43824f644da93d10f75f5ec95e"

      def install
        bin.install "mantil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "releases.mantil.io/v0.1.20/mantil_0.1.20_Linux_arm64.tar.gz"
      sha256 "28ecaf25e1a9a7c90805f8edab9a4c2e5db284a089aa536511b0ea12d286ae5c"

      def install
        bin.install "mantil"
      end
    end
    if Hardware::CPU.intel?
      url "releases.mantil.io/v0.1.20/mantil_0.1.20_Linux_x86_64.tar.gz"
      sha256 "b64390afaac473feceb75f059d3b76d2439b3638f13e11041a4567e49ef1ef0b"

      def install
        bin.install "mantil"
      end
    end
  end

  depends_on "go"
end
