# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantil < Formula
  desc "Mantil CLI"
  homepage ""
  version "0.1.8"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://mantil-downloads.s3.eu-central-1.amazonaws.com/releases/cli/v0.1.8/mantil_0.1.8_Darwin_x86_64.tar.gz"
      sha256 "a727bac1be8a3f759c2d05059f8174b5745a8dd49e4f8daf522ef182093dbc03"
    end
    if Hardware::CPU.arm?
      url "https://mantil-downloads.s3.eu-central-1.amazonaws.com/releases/cli/v0.1.8/mantil_0.1.8_Darwin_arm64.tar.gz"
      sha256 "f0ba2b22a89c372504b805f092f89237f525b1c873bc500488094a59d261de3a"
    end
  end

  depends_on "go"

  def install
    bin.install "mantil"
  end
end
